name: Test
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on gh pages
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm run ng deploy:dev
