name: Test
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on gh pages
        uses: actions/checkout@v2
      - name: Use Node.js 16.5
        uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run ng deploy
